update to JoltPhysics 5.3.0, but only compiling in debug mode due to issue with USE_ASSERTS/JPH_ENABLE_ASSERTS, get undefined reference to `JPH::AssertFailed'